[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
d_fiverr = "6t7FU5ZA1A38w4tgAPVqR3bYx9CwoctqgPtQ7oFMJtn"

[registry]
url = "https://api.apr.dev"

[programs.devnet]
d_fiverr = "6t7FU5ZA1A38w4tgAPVqR3bYx9CwoctqgPtQ7oFMJtn"
# programdata = "CrRa5MvEM4iBp4qkTiywNMYdRWCywzHcBGWcwHs32UuG"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.17"