[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
d_fiverr = "AmfNtSvJJdAzbdPqgYM1Hz242Ub6bnE9zEZV1h4Z3A4q"

[registry]
url = "https://api.apr.dev"

[programs.devnet]
d_fiverr = "53f9PzxmMi2ztWzTvM1pNgJXhhxyuPNCMNk6y9DPfELZ"

[programs.testnet]
d_fiverr = "53f9PzxmMi2ztWzTvM1pNgJXhhxyuPNCMNk6y9DPfELZ"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.22"