import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import {Navbar} from "@/components/navbar";
import { getServerSession, Session } from "next-auth";
import { authConfig } from "@/lib/auth";
import { getLastRole } from "./actions/buyer/role";
import { UserRole } from "@prisma/client";
import { ThemeProvider } from 'next-themes';
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Decentralized fiverr",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authConfig)
  // console.log(session)
  const role = session && await getLastRole(session?.user.id)
  return (
    <html lang="en">
    <Suspense fallback={<Loading/>}>
      <body className={inter.className}>
        <Providers>
          <Navbar session={session}/>
          {children}
        </Providers>
      </body>
    </Suspense >
    </html>
  );
}
