import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Navbar from "@/components/navbar";
import { RoleBasedRedirect } from "@/components/new";
import { getServerSession, Session } from "next-auth";
import { authConfig } from "@/lib/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Decentralized fiverr",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authConfig)
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar session={session}/>
          <RoleBasedRedirect session={session}/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
